# 异常处理
## throw语句
### 语法
```c++
throw 表达式
```
执行表达式，并跳出函数。会将代码跳至能处理该表达式的最近的catch语句中。
### 例子
```c++
if(b==0) throw runtime_error("Enter right b");
```
throw将返回一个`runtime_error`对象。
## try语句
### 语法
```c++
try {保护代码;}
catch(异常声明1){
    异常处理代码;
}
catch(···){
    ··· 
}
```
<div class="warning"><p>保护代码处声明的变量无法在<code>catch</code>处使用</p></div>

## 例子
```c++
 try{
    if (b==0) throw runtime_error;
}
catch(runtime_error err){
    cout<<err.what()<<endl;
    }
```

其中`what()`为`runtime_error`的成员函数。其会将`err`的详细内容以`string`类返回。
## 异常类
### stdexcept定义的异常
![exceptions_in_cpp](/assets/exceptions_in_cpp.png)

![Snipaste_2020-08-22_18-02-23](/assets/Snipaste_2020-08-22_18-02-23.png)